### ISSUE TITLE
Add timezone in config?

### ISSUE THREAD

**Issue by doctarrwho** [tedpearson/electric-usage-downloader#12]
After importing the data, I noticed that the times in grafana were off by 2 hours. I'm in MST, and the offset being set in `parser.go` utilizes EST:

`zone, err := time.LoadLocation("America/New_York")`

I changed the timezone on this line, and that fixed the offset for me in grafana. It would be nice to have the tz option in config.yaml as well.

**Comment by tedpearson** [comment]
Definitely another instance where I first developed the project for my own usage, and didn't make it configurable. I can add this.

**Comment by tedpearson** [comment]
Update:

The issue is not so much that this project was for my own usage and not configurable, but instead that the SmartHub API returns "unix timestamps" that are in the local utility's timezone. My utility configured their SmartHub to return EST timestamps, which I assumed would be true for every SmartHub deployment. A more appropriate choice for the SmartHub developers would have been to always return UTC timestamps, and we never would have had this issue.

I've added a new configuration, `timezone`, in the `smarthub` section of the config. I don't want to rely on the user's machine having the correct timezone, as that may not be the same as the timezone used by their utility.

The fix is available in [v2.3.0](https://github.com/tedpearson/electric-usage-downloader/releases/tag/v2.3.0).
